Delete input-more-prev directory
causing error on build- removing to see if it helps

error[E0432]: unresolved imports `input_core::MultiClickHandleRequest`, `input_core::TimedMultiClickError`, `input_core::TimedMultiClickEventData`
 --> /home/amir/.cargo/git/checkouts/sunshine-d4a071baa88c12de/3ca0186/input-more-prev/src/timed_event.rs:5:29
  |
5 |     LongPressHandleRequest, MultiClickHandleRequest, TimedLongClickError, TimedLongPressEventData,
  |                             ^^^^^^^^^^^^^^^^^^^^^^^ no `MultiClickHandleRequest` in the root
6 |     TimedMultiClickError, TimedMultiClickEventData, TimedPressError, TimedReleaseError,
  |     ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^ no `TimedMultiClickEventData` in the root
  |     |
  |     no `TimedMultiClickError` in the root
  |     help: a similar name exists in the module: `TimedLongClickError`

error[E0107]: this enum takes 0 generic arguments but 1 generic argument was supplied
  --> /home/amir/.cargo/git/checkouts/sunshine-d4a071baa88c12de/3ca0186/input-more-prev/src/pointer_event.rs:11:38
   |
11 |     ) -> Context<Re::Output, (Option<PointerChangeEventData<Sw>>, Ev3)>
   |                                      ^^^^^^^^^^^^^^^^^^^^^^---- help: remove these generics
   |                                      |
   |                                      expected 0 generic arguments
   |